version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stickto-postgres
    environment:
      POSTGRES_DB: Stickto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stickto123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: stickto-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stickto.com
      PGADMIN_DEFAULT_PASSWORD: sticktoadmin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      GUNICORN_LIMIT_REQUEST_FIELD_SIZE: '8190'
      GUNICORN_LIMIT_REQUEST_FIELDS: '100'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
